### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by mononz** [FCLM/Fclm-Website#13]
change
 > Every Sunday @ 7pm (QLD) - Join us
to 
 > Every Sunday and Wednesday @ 7pm (VIC/NSW) - Join us
(Or whatever is appropriate. maybe NZ time too (9pm NZT)

Separate the following into two paragraphs

> Todays active leadership includes Mono and Spudles. Other leaders of FCLM have included DropbearOwnage, EatenAlive and Acherlon and Fappy.

**Comment by Dalordish** [comment]
Solved in #14
